# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes', '0002_leader_bio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('method', models.CharField(max_length=40)),
                ('description', models.TextField(default='blank', max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='leader',
            name='age',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='leader',
            name='hero_name',
            field=models.CharField(default='blank', max_length=40),
        ),
        migrations.AddField(
            model_name='power',
            name='leader',
            field=models.ManyToManyField(to='heroes.Leader'),
        ),
    ]
