# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 13:29
from __future__ import unicode_literals

from django.db import migrations, models
import posts.validators


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='brand_email',
            field=models.EmailField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='post',
            name='brand',
            field=models.CharField(max_length=50, validators=[posts.validators.min_validation]),
        ),
        migrations.AlterField(
            model_name='post',
            name='brand_type',
            field=models.CharField(max_length=80, validators=[posts.validators.min_validation]),
        ),
        migrations.AlterField(
            model_name='post',
            name='description',
            field=models.TextField(validators=[posts.validators.min_validation]),
        ),
    ]
